# Dependencies
markdown: 		redcarpet
highlighter: 	pygments
redcarpet:
  extensions: 	["tables"]

# Permalinks
permalink:		pretty

# Site settings
title: 			My Blog
url: 			http://jgiovaresco.github.io
description: 	A blog software development

author :
  name : 		Julien Giovaresco
  email : 		contactme@giovaresco.fr
  github : 		jgiovaresco
  twitter : 	jgiovaresco

paginate:		1

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from