# Site settings
title: My Blog
markdown: redcarpet
highlighter: pygments

description: A blog software development
url: http://jgiovaresco.github.io

author :
  name : Julien Giovaresco
  email : contactme@giovaresco.fr
  github : jgiovaresco
  twitter : jgiovaresco

# Config for Jekyll rake boilerplate
#post:
#  template: _templates/post.txt
#  extension: md
#page:
#  template: _templates/page.txt
#  extension: md
#editor: atom